### PR TITLE
Func signatures windows support

### PR DESCRIPTION
**Pull request by benitogf**

### CODE REVIEW

**Comment by haakonnessjoen** [comment]
Did you change your mind?

**Comment by benitogf** [comment]
happy to open the pr if you would like to take a look 👍 was trying to merge to my fork and opened by mistake 😄

**Comment by haakonnessjoen** [comment]
Please do a pr when you feel your changes are done and stable, would be nice with windows support in the same package, did you ever find out the reason for the crashes with your ndi reads?

**Comment by benitogf** [comment]
I gave up on the approach of creating ndi clients to do the preview, and instead I update the mjpeg when I write to the ndi channel only, not ideal, still would like to find a better way to provide "preview" on the browser

Still testing the signature changes, I asked in the purego discord and aparently this was causing a crash on the ndi send (and possibly ndi read?) due to the params being cleared by GC since they were just uintptr and not actual pointers, so far no crash with these changes

sure will create a pr when I have tested a bit more 👍

**Pull request closed without merging**
